name: cd

on:
  push:
    tags:
      - '**'

jobs:
  pypi:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@feat/build_multiple_wheels
    secrets: inherit
    with:
      build_args: '--sdist'
      platforms: "['ubuntu-latest','macos-latest','windows-latest']"
      pyversions: "['38','39','310','311','312','313']"
