name: ci

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  quality_assurance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install ruff
      - run: ruff check
      - run: ruff format --check

  setup_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - name: install earthkit-hydro
        shell: bash -l {0}
        run: pip install .[test]
      - name: run tests
        shell: bash -l {0}
        run: pytest