name: test-cd

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi-binwheel.yml@feat/build_multiple_wheels
    secrets: inherit
    with:
      platforms: "['ubuntu-latest','macos-latest','windows-latest']"
      pyversions: "['38']"
      testpypi: true
