name: test-cd

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@feat/build_multiple_wheels
    secrets: inherit
    with:
      testpypi: true
      build_args: '--sdist'
